require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'BetterTusClientExample' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'react-native-better-tus-client', :path => '../..'
  pod 'TUSKit', :git => 'https://github.com/hannojg/TUSKit.git', :branch => 'patch-1'
  
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({ 'Flipper' => '0.74.0' })
  post_install do |installer|
    flipper_post_install(installer)
  end
end
